/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import constants.Constants;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import session.Session;

/**
 *
 * @author lukabaljak
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form FMain
     */
    
    private String ulogovaniKorisnik;
    public FMain(String ulogovaniKorisnik) {
        initComponents();
        maximizeForm();
        this.ulogovaniKorisnik = ulogovaniKorisnik;
        jLabelUlogovaniKorisnik.setText("Ulogovani korisnik: " + ulogovaniKorisnik +" ");
               
        jLabelUlogovaniKorisnik.setHorizontalAlignment(SwingConstants.RIGHT);
//        try {
//            Socket socket = new Socket("localhost", 9090);
//            Session.getInstance().getMap().put(Constants.SOCKET, socket);
//            DataOutputStream out = new DataOutputStream(socket.getOutputStream());
//            out.writeUTF(ulogovaniKorisnik);
//            out.flush(); 
//        } catch (IOException ex) {
//           
//            JOptionPane.showMessageDialog(rootPane, "Doslo je do greske prilikom povezivanja na server. Molimo da probate opet kasnije.");
//            ugasiFormu();
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUlogovaniKorisnik = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTeniser = new javax.swing.JMenu();
        jMenuItemTeniserKreirajNovog = new javax.swing.JMenuItem();
        jMenuItemTeniserPrikaziRangListu = new javax.swing.JMenuItem();
        jMenuTurnir = new javax.swing.JMenu();
        jMenuItemTurnirKreirajNovi = new javax.swing.JMenuItem();
        jMenuItemTurnirPretrazi = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATP tur");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuTeniser.setText("Teniser");

        jMenuItemTeniserKreirajNovog.setText("Kreiraj novog");
        jMenuItemTeniserKreirajNovog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTeniserKreirajNovogActionPerformed(evt);
            }
        });
        jMenuTeniser.add(jMenuItemTeniserKreirajNovog);

        jMenuItemTeniserPrikaziRangListu.setText("Prikaži rang listu");
        jMenuItemTeniserPrikaziRangListu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTeniserPrikaziRangListuActionPerformed(evt);
            }
        });
        jMenuTeniser.add(jMenuItemTeniserPrikaziRangListu);

        jMenuBar1.add(jMenuTeniser);

        jMenuTurnir.setText("Turnir");

        jMenuItemTurnirKreirajNovi.setText("Kreiraj novi");
        jMenuItemTurnirKreirajNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTurnirKreirajNoviActionPerformed(evt);
            }
        });
        jMenuTurnir.add(jMenuItemTurnirKreirajNovi);

        jMenuItemTurnirPretrazi.setText("Pretrazi");
        jMenuItemTurnirPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTurnirPretraziActionPerformed(evt);
            }
        });
        jMenuTurnir.add(jMenuItemTurnirPretrazi);

        jMenuBar1.add(jMenuTurnir);

        jMenuAbout.setText("About");
        jMenuBar1.add(jMenuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUlogovaniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 211, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelUlogovaniKorisnik, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTurnirKreirajNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurnirKreirajNoviActionPerformed
        FTurnir turnir = new FTurnir(this, true, null);
        turnir.setVisible(true);
    }//GEN-LAST:event_jMenuItemTurnirKreirajNoviActionPerformed

    private void jMenuItemTeniserKreirajNovogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTeniserKreirajNovogActionPerformed
        FTeniser teniser = new FTeniser(this, true);
        teniser.setVisible(true);
    }//GEN-LAST:event_jMenuItemTeniserKreirajNovogActionPerformed

    private void jMenuItemTeniserPrikaziRangListuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTeniserPrikaziRangListuActionPerformed
        JDialog rangLista = new FRangLista(this, true, Constants.PREGLED_RANG_LISTE);
        rangLista.setVisible(true);
    }//GEN-LAST:event_jMenuItemTeniserPrikaziRangListuActionPerformed

    private void jMenuItemTurnirPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurnirPretraziActionPerformed
        JDialog pretragaTurnira = new FPretraziTurnire(this, true);
        pretragaTurnira.setVisible(true);

    }//GEN-LAST:event_jMenuItemTurnirPretraziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMain("niko").setVisible(true);
            }
        });
    }
    
    private void maximizeForm() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelUlogovaniKorisnik;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemTeniserKreirajNovog;
    private javax.swing.JMenuItem jMenuItemTeniserPrikaziRangListu;
    private javax.swing.JMenuItem jMenuItemTurnirKreirajNovi;
    private javax.swing.JMenuItem jMenuItemTurnirPretrazi;
    private javax.swing.JMenu jMenuTeniser;
    private javax.swing.JMenu jMenuTurnir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void ugasiFormu() {
        dispose();
    }
}
